
import javax.swing.JOptionPane;


public class Dashboard extends javax.swing.JFrame {

     // User role and information
    private String userRole; // "ADMIN" or "CLERK"
    private String username;
      /**
     * Creates new form Dashboard
     * @param userRole The role of the logged-in user ("ADMIN" or "CLERK")
     * @param username The username of the logged-in user
     */
    public Dashboard(String userRole, String username) {
        this.userRole = userRole;
        this.username = username;
        initComponents();
        configureRoleBasedAccess();
    }
    
    public Dashboard() {
          // Get user data from loginPage static variables
        if (loginPage.isLoggedIn) {
            this.userRole = loginPage.loggedInUserRole;
            this.username = loginPage.loggedInUsername;
        } else {
            // Fallback - redirect to login
            this.dispose();
            new loginPage().setVisible(true);
            return;
        }
        initComponents();
        configureRoleBasedAccess();      
    }
    
        private void configureRoleBasedAccess() {
        // Update welcome message with user info
        jLabel1.setText("Welcome " + username + " (" + userRole + ")");
        
        if ("CLERK".equals(userRole)) {
            // Hide admin-only features for clerks
            AddUser.setVisible(false);  
            Customer.setVisible(false);         // User Management - Admin only
            Backup.setVisible(false);            // Database Backup - Admin only
            //Settings.setVisible(false);          // Settings - Admin only
            //AuditLogs.setVisible(false);         // Audit Logs - Admin only
            
            // Modify inventory access (view only for clerks)
            Inventory.setText("View Inventory");
            Inventory.setToolTipText("View-only access to inventory");
            
             // Add visual indicator for limited access
            Sales.setToolTipText("Limited sales access");
            //Customer.setToolTipText("Customer management access");
            
            // Adjust panel layout for fewer options
            adjustPanelLayoutForClerk();
            
               // Show a welcome message for clerks
            showClerkWelcomeMessage();
        } else if ("ADMIN".equals(userRole)) {
            // Full access for admin
            AddUser.setToolTipText("Full user management access");
            Backup.setToolTipText("Database backup and restore");
            Inventory.setToolTipText("Full inventory management");
            Sales.setToolTipText("Full sales management");
            Customer.setToolTipText("Full customer management");
        } 
    }
        
           /**
     * Show welcome message for clerk users
     */
    private void showClerkWelcomeMessage() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(this, 
                "Welcome, " + username + "!\n\n" +
                "You are logged in as a CLERK.\n" +
                "Available functions:\n" +
                "• Manage Customers\n" +
                "• View Inventory\n" +
                "• Manage Sales\n\n" +
                "Note: User management and backup functions are admin-only.",
                "Clerk Access", 
                JOptionPane.INFORMATION_MESSAGE);
        });
    }
    
    /**
     * Adjust panel layout when fewer options are visible (for clerks)
     */
    private void adjustPanelLayoutForClerk() {
        // Recalculate panel layout to accommodate hidden components
        jPanel1.revalidate();
        jPanel1.repaint();
    }
        /**
     * Check if user has admin privileges
     */
    private boolean hasAdminAccess() {
        return "Administrator".equals(userRole);
    }
    
    /**
     * Show access denied message
     */
    private void showAccessDenied(String feature) {
        JOptionPane.showMessageDialog(this, 
            "Access Denied!\n\n" +
            "You need ADMIN privileges to access: " + feature + "\n" +
            "Current role: " + userRole + "\n\n" +
            "Please contact your system administrator for access.",
            "Access Denied", 
            JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AddUser = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        Sales = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        Backup = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to our Business ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        AddUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddUser.setForeground(new java.awt.Color(255, 255, 255));
        AddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profile.png"))); // NOI18N
        AddUser.setText("Add User");
        AddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserMouseClicked(evt);
            }
        });

        Inventory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/inventory.png"))); // NOI18N
        Inventory.setText("Manage Inventory");
        Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryMouseClicked(evt);
            }
        });

        Sales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sales.setForeground(new java.awt.Color(255, 255, 255));
        Sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/direct-marketing.png"))); // NOI18N
        Sales.setText("Manage Sales");
        Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesMouseClicked(evt);
            }
        });

        Customer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Customer.setForeground(new java.awt.Color(255, 255, 255));
        Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rating.png"))); // NOI18N
        Customer.setText("Manage Customers");
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });

        Backup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Backup.setForeground(new java.awt.Color(255, 255, 255));
        Backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backup.png"))); // NOI18N
        Backup.setText("Backup / Restore");
        Backup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Inventory, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(Backup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Customer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Backup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, -1, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Inventory-Management.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 86, 500, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
       int logout = JOptionPane.showConfirmDialog(null, 
            "Do you want to logout from the system?\n\nUser: " + username + " (" + userRole + ")",
            "Confirm Logout",JOptionPane.YES_NO_OPTION);
        if(logout == 0) {
            // Clear session data
            loginPage.loggedInUsername = "";
            loginPage.loggedInUserRole = "";
            loginPage.loggedInFullName = "";
            loginPage.isLoggedIn = false;
            
            setVisible(false);
            new loginPage().setVisible(true);
        }
    }//GEN-LAST:event_LogoutMouseClicked

    private void AddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserMouseClicked
        if (!hasAdminAccess()) {
            showAccessDenied("User Management");
            return;
        }
        
        setVisible(false);
        new AddUserPage().setVisible(true);
    }//GEN-LAST:event_AddUserMouseClicked

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
            setVisible(false);
            new CustomerPage().setVisible(true);
    }//GEN-LAST:event_CustomerMouseClicked

    private void InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseClicked
        setVisible(false);
        
        if (hasAdminAccess()) {
            // Admin gets full access
            new InventoryPage().setVisible(true);
        } else {
            // Clerk gets view-only access
            new InventoryPage().setVisible(true);
        }
    }//GEN-LAST:event_InventoryMouseClicked

    private void SalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMouseClicked
        // TODO add your handling code here:
        // Both clerks and admins can access sales, but with different permissions
        setVisible(false);
        
        if (hasAdminAccess()) {
            new SalesPage().setVisible(true);
        } else {
            // Clerks can make sales but may have limited access to reports/modifications
            new SalesPage().setVisible(true);
        }
    }//GEN-LAST:event_SalesMouseClicked

    private void BackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackupMouseClicked
        // TODO add your handling code here:
                if (!hasAdminAccess()) {
            showAccessDenied("User Management");
            return;
        }
        
        setVisible(false);
        new BackupRestoreFrame().setVisible(true);
    }//GEN-LAST:event_BackupMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddUser;
    private javax.swing.JLabel Backup;
    private javax.swing.JLabel Customer;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Sales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
